apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prem-operator-chart.fullname" . }}-manager-role
  labels:
  {{- include "prem-operator-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - premlabs.io
  resources:
  - aideployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - premlabs.io
  resources:
  - aideployments/finalizers
  verbs:
  - update
- apiGroups:
  - premlabs.io
  resources:
  - aideployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - premlabs.io
  resources:
  - aimodelmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - premlabs.io
  resources:
  - aimodelmaps/finalizers
  verbs:
  - update
- apiGroups:
  - premlabs.io
  resources:
  - aimodelmaps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - premlabs.io
  resources:
  - autonodelabelers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - premlabs.io
  resources:
  - autonodelabelers/finalizers
  verbs:
  - update
- apiGroups:
  - premlabs.io
  resources:
  - autonodelabelers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prem-operator-chart.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: prem-operator
    app.kubernetes.io/part-of: prem-operator
  {{- include "prem-operator-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "prem-operator-chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "prem-operator-chart.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'