apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "premlabs.io/v1alpha1",
          "kind": "AIDeployment",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "prem-operator",
              "app.kubernetes.io/instance": "aideployment-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "aideployment",
              "app.kubernetes.io/part-of": "prem-operator"
            },
            "name": "aideployment-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "premlabs.io/v1alpha1",
          "kind": "AIModelMap",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "prem-operator",
              "app.kubernetes.io/instance": "aimodelmap-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "aimodelmap",
              "app.kubernetes.io/part-of": "prem-operator"
            },
            "name": "aimodelmap-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "premlabs.io/v1alpha1",
          "kind": "AutoNodeLabeler",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "prem-operator",
              "app.kubernetes.io/instance": "autonodelabeler-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "autonodelabeler",
              "app.kubernetes.io/part-of": "prem-operator"
            },
            "name": "autonodelabeler-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-04-29T09:18:26Z"
    operators.operatorframework.io/builder: operator-sdk-unknown
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: prem-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AIDeployment is the Schema for the AIDeployment API
      displayName: AIDeployment
      kind: AIDeployment
      name: aideployments.premlabs.io
      version: v1alpha1
    - description: AIModelMap is the Schema for the aimodelmaps API
      displayName: AIModel Map
      kind: AIModelMap
      name: aimodelmaps.premlabs.io
      version: v1alpha1
    - description: AutoNodeLabeler is the Schema for the autonodelabelers API
      displayName: Auto Node Labeler
      kind: AutoNodeLabeler
      name: autonodelabelers.premlabs.io
      version: v1alpha1
  description: Simplified operator for deploying ML models
  displayName: prem-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - premlabs.io
          resources:
          - aideployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - premlabs.io
          resources:
          - aideployments/finalizers
          verbs:
          - update
        - apiGroups:
          - premlabs.io
          resources:
          - aideployments/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - premlabs.io
          resources:
          - aimodelmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - premlabs.io
          resources:
          - aimodelmaps/finalizers
          verbs:
          - update
        - apiGroups:
          - premlabs.io
          resources:
          - aimodelmaps/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - premlabs.io
          resources:
          - autonodelabelers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - premlabs.io
          resources:
          - autonodelabelers/finalizers
          verbs:
          - update
        - apiGroups:
          - premlabs.io
          resources:
          - autonodelabelers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: prem-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: prem-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: prem-operator
          control-plane: controller-manager
        name: prem-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: controller:latest
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: prem-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: prem-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ai
  - ml
  links:
  - name: Prem Operator
    url: https://prem-operator.domain
  maintainers:
  - email: swarnim@premai.io
    name: premai
  maturity: alpha
  provider:
    name: premlabs
  version: 0.0.1
