# permissions for end users to view aideployment.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: aideployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: prem-operator
    app.kubernetes.io/part-of: prem-operator
    app.kubernetes.io/managed-by: kustomize
  name: aideployment-viewer-role
rules:
- apiGroups:
  - premlabs.io
  resources:
  - aideployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - premlabs.io
  resources:
  - aideployment/status
  verbs:
  - get
