# permissions for end users to edit autonodelabelers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: autonodelabeler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: prem-operator
    app.kubernetes.io/part-of: prem-operator
    app.kubernetes.io/managed-by: kustomize
  name: autonodelabeler-editor-role
rules:
- apiGroups:
  - premlabs.io
  resources:
  - autonodelabelers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - premlabs.io
  resources:
  - autonodelabelers/status
  verbs:
  - get
