apiVersion: v1
kind: Namespace
metadata:
  name: shell
  labels:
    premai.io/util: shell
---
apiVersion: v1
kind: Pod
metadata:
  name: shell
  namespace: shell
  labels:
    premai.io/util: shell
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  volumes:
  - name: root
    hostPath:
      path: /
  containers:
  - image: alpine
    name: shell
    securityContext:
      privileged: true
      procMount: Unmasked
      seccompProfile:
        type: Unconfined
    command:
    - /bin/sh
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /
      name: root
