apiVersion: premlabs.io/v1alpha1
kind: AIDeployment 
metadata:
  name: simple
  namespace: default
spec:
  # single node instance
  # no dashboard support 
  engine:
    name: "localai" 
  endpoint:
    - domain: "foo.127.0.0.1.nip.io"
      port: 8080 
  models:
    - uri: tinyllama-chat
  service:
    annotations:
    labels:
  ingress:
    annotations:
    labels:
  deployment:
    annotations:
    labels:
    resources:
      requests:
        cpu: 8
        memory: "3Gi"
  env:
    - name: "DEBUG"
      value: "true"
