apiVersion: premlabs.io/v1alpha1
kind: AIDeployment 
metadata:
  name: simple
  namespace: default
spec:
  # single node instance
  # no dashboard support 
  engine:
    name: "localai" 
  endpoint:
    - domain: "foo.127.0.0.1.nip.io"
      port: 8080 
  models:
    - custom:
        format: "gguf" 
        name: "gpt-4" 
        url: "https://huggingface.co/afrideva/llama2_xs_460M_experimental-GGUF/resolve/main/llama2_xs_460m_experimental.q8_0.gguf?download=true"
        checksum: "sha1:"
  service:
    annotations:
    labels:
  ingress:
    annotations:
    labels:
  deployment:
    annotations:
    labels:
  env:
    - name: "DEBUG"
      value: "true"
