apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "saas-controller.fullname" . }}-manager-role
  labels:
  {{- include "saas-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.premlabs.io
  resources:
  - simpledeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.premlabs.io
  resources:
  - simpledeployments/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.premlabs.io
  resources:
  - simpledeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "saas-controller.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: saas-operator
    app.kubernetes.io/part-of: saas-operator
  {{- include "saas-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "saas-controller.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "saas-controller.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'