---
name: 'test controller'

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
      - name: e2e-tests
        run: |
          make kind-e2e-tests